// FILE: app/layout.tsx
// _______________________________________________

import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { WithChildren } from "@/types/utilities.types";
import { Figtree } from "next/font/google";
// _______________________________________________

const font = Figtree({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};
// _______________________________________________


// _______________________________________________

export default function RootLayout({ children }: WithChildren) {
  
  // _________________ [functions] ___________________
  
  
  // _________________________________________________
  return (
    <html lang="en">
			<body className={ font.className }>
			<Navbar />
			<main>
				{ children }
			</main>
			<Footer />
			</body>
		</html>
  );
}
// _______________________________________________