// FILE: app/layout.tsx
// _______________________________________________

import './globals.css';
import { Figtree } from 'next/font/google';
import { ReactNode } from 'react';
// _______________________________________________

const font = Figtree({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};
// _______________________________________________

//! exporting this custom `WithChildren` type
//! to be used or placed in its own file later
export type WithChildren<Value = {}> = Value & {
	children?: ReactNode;
};
// _______________________________________________

export default function RootLayout({ children }: WithChildren) {
	
	// _________________ [functions] ___________________
	
	
	// _________________________________________________
	return (
		<html lang="en">
			<body className={ font.className }>
			{ children }
			</body>
		</html>
	);
}
// _______________________________________________