# FILE: .prettierrc.yaml
# ________________________________

printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
jsxSingleQuote: true
trailingComma: "all"
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: "always"
endOfLine: "lf"
# ________________________________